--------------------------------------------------------
-- Archivo creado  - domingo-diciembre-29-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package USP_COMISION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "C##ASISTENCIA"."USP_COMISION" AS TYPE REF_TYPE IS REF CURSOR;

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 
PROCEDURE NUEVO(
    P_VDESCRIPCION IN VARCHAR2,
    P_IIDOCUMENTO IN NUMBER,
    P_VDOCUMENTO IN VARCHAR2,
    P_DFECHASALIDA IN TIMESTAMP,
    P_DFECHARETORNO IN TIMESTAMP,
    P_DFECHADOCUMENTO IN TIMESTAMP,
    P_IIDPADRE IN NUMBER,
    P_IIDPAIS IN NUMBER,
    P_IIDDEPARTAMENTO IN NUMBER,
    P_IIDPROVINCIA IN NUMBER,
    P_IIDDISTRITO IN NUMBER,
    P_IIDOFICINA IN NUMBER,
    P_IIDUSUARIOREGISTRA IN NUMBER,
    R_RESULTADO OUT NUMBER
   );
   
  PROCEDURE INSERTARDETALLECOMISION(
    P_IIDCOMISION IN NUMBER,
    P_IIDEMPLEADO IN NUMBER
   -- P_DFECHASALIDA IN TIMESTAMP,
    --P_DFECHARETORNO IN TIMESTAMP,
    --R_RESULTADO OUT NUMBER
   );  
  PROCEDURE LISTARPERSONAL(
    P_FILTERS IN VARCHAR2,
    R_RESULTADO OUT REF_TYPE
  );
  PROCEDURE LISTAR(
    P_LIMIT IN NUMBER,
    P_START IN NUMBER,
    P_SORT IN VARCHAR2,
    P_FILTERS IN VARCHAR2,
    R_RESULTADO OUT REF_TYPE,
    R_TOTAL OUT NUMBER  
  );
  PROCEDURE LISTARDETALLEPERSONAL(
    P_LIMIT IN NUMBER,
    P_START IN NUMBER,
    P_SORT IN VARCHAR2,
    P_FILTERS IN VARCHAR2,
    R_RESULTADO OUT REF_TYPE,
    R_TOTAL OUT NUMBER  
  );
  
  /*PROCEDURE ELIMINAREMPLEADO(
      P_IIDEMPLEADO IN NUMBER,
      P_IIDCOMISION IN NUMBER
  );*/
  
  PROCEDURE EDITAR(
    P_IIDCOMSION IN NUMBER,
    P_VDESCRIPCION IN VARCHAR2,
    P_IIDOCUMENTO IN NUMBER,
    P_VDOCUMENTO IN VARCHAR2,
    P_DFECHASALIDA IN TIMESTAMP,
    P_DFECHARETORNO IN TIMESTAMP,
    P_DFECHADOCUMENTO IN TIMESTAMP,
    P_IIDPAIS IN NUMBER,
    P_IIDDEPARTAMENTO IN NUMBER,
    P_IIDPROVINCIA IN NUMBER,
    P_IIDDISTRITO IN NUMBER, 
    P_IIDOFICINA IN NUMBER,
    P_IIDUSUARIOREGISTRA IN NUMBER,
    R_RESULTADO OUT NUMBER
  );
  
  /*PROCEDURE EDITARDETALLECOMISION(
    P_IIDCOMISION IN NUMBER,
    P_IIDEMPLEADO IN NUMBER
  );*/
  
  PROCEDURE INSERTARHISTORIALCOMISION(
    P_IIDCOMISION IN NUMBER,
    P_IIDUSUARIO IN NUMBER,
    P_IIDESTADO IN NUMBER
  );
  
  PROCEDURE INSERTARAMPLIARHIST_COMISION(
    P_IIDCOMISIONANTERIOR IN NUMBER,
    P_IIDCOMISIONNUEVO IN NUMBER,
    P_IIDUSUARIO IN NUMBER,
    R_RESULTADO OUT NUMBER
  );  
  PROCEDURE LISTARHISTORIALCOMISION(
    P_FILTERS IN VARCHAR2,
    R_RESULTADO OUT REF_TYPE
  );
  PROCEDURE APROBAR(
    P_IIDCOMISION IN NUMBER,
    P_IIDUSUARIOREGISTRA IN NUMBER,
    R_RESULTADO OUT NUMBER
  );
  
  PROCEDURE ELIMINARDENEGARANULAR(
    P_IIDCOMISION IN NUMBER,
    P_IIFLAG IN NUMBER,
    P_VDESCRIPCION IN VARCHAR2,
    P_IIDUSUARIOREGISTRA IN NUMBER,
    R_RESULTADO OUT NUMBER  
  );
END USP_COMISION;

/
--------------------------------------------------------
--  DDL for Package Body USP_COMISION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "C##ASISTENCIA"."USP_COMISION" AS
 PROCEDURE NUEVO(
    P_VDESCRIPCION IN VARCHAR2,
    P_IIDOCUMENTO IN NUMBER,
    P_VDOCUMENTO IN VARCHAR2,
    P_DFECHASALIDA IN TIMESTAMP,
    P_DFECHARETORNO IN TIMESTAMP,
    P_DFECHADOCUMENTO IN TIMESTAMP,
    P_IIDPADRE IN NUMBER,
    P_IIDPAIS IN NUMBER,
    P_IIDDEPARTAMENTO IN NUMBER,
    P_IIDPROVINCIA IN NUMBER,
    P_IIDDISTRITO IN NUMBER,
    P_IIDOFICINA IN NUMBER,
    P_IIDUSUARIOREGISTRA IN NUMBER,
    R_RESULTADO OUT NUMBER
   )AS
   BEGIN
    IF(P_IIDPADRE=0) THEN 
      INSERT INTO COMISION(VDESCRIPCION,IIDOCUMENTO,VDOCUMENTO,DFECHASALIDA,DFECHARETORNO,DFECHADOCUMENTO,IIDUSUARIOREGISTRA,DFECHAREGISTRA,IIDPAIS,IIDDEPARTAMENTO,IIDPROVINCIA,IIDDISTRITO,IIDOFICINA) 
      VALUES(P_VDESCRIPCION,P_IIDOCUMENTO,P_VDOCUMENTO,P_DFECHASALIDA,P_DFECHARETORNO,P_DFECHADOCUMENTO,P_IIDUSUARIOREGISTRA,SYSDATE,P_IIDPAIS,P_IIDDEPARTAMENTO,P_IIDPROVINCIA,P_IIDDISTRITO,P_IIDOFICINA)
      RETURNING IIDCOMISION INTO R_RESULTADO;      
    ELSE--AMPLIAR COMISION
      INSERT INTO COMISION(VDESCRIPCION,IIDOCUMENTO,VDOCUMENTO,DFECHASALIDA,DFECHARETORNO,DFECHADOCUMENTO,IIDPADRE,IIDUSUARIOREGISTRA,DFECHAREGISTRA,IIDDEPARTAMENTO,IIDPROVINCIA,IIDDISTRITO,IIDPAIS,IIDOFICINA) 
      VALUES(P_VDESCRIPCION,P_IIDOCUMENTO,P_VDOCUMENTO,P_DFECHASALIDA,P_DFECHARETORNO,P_DFECHADOCUMENTO,P_IIDPADRE,P_IIDUSUARIOREGISTRA,SYSDATE,P_IIDDEPARTAMENTO,P_IIDPROVINCIA,P_IIDDISTRITO,P_IIDPAIS,P_IIDOFICINA)
      RETURNING IIDCOMISION INTO R_RESULTADO;
    END IF;      
   END NUEVO;
   
   PROCEDURE INSERTARDETALLECOMISION(
    P_IIDCOMISION IN NUMBER,
    P_IIDEMPLEADO IN NUMBER
   -- P_DFECHASALIDA IN TIMESTAMP,
   -- P_DFECHARETORNO IN TIMESTAMP,
   -- R_RESULTADO OUT NUMBER
   )AS
   V_TOTAL INT;
   BEGIN
    --SELECT COUNT(*) INTO V_TOTAL FROM COMISION COM INNER JOIN DETALLE_COMISION DC ON COM.IIDCOMISION=DC.IIDCOMISION WHERE 1=1 AND COM.BHABILITADO=1
    --AND COM.DFECHASALIDA<=P_DFECHARETORNO   
    --AND COM.DFECHARETORNO>= P_DFECHASALIDA 
   -- AND DC.IIDEMPLEADO=P_IIDEMPLEADO; 
   -- IF(V_TOTAL=0) THEN 
      INSERT INTO DETALLE_COMISION(IIDCOMISION,IIDEMPLEADO,DFECHAREGISTRA) VALUES(P_IIDCOMISION,P_IIDEMPLEADO,SYSDATE);
      --R_RESULTADO:=2;
     -- ELSE
     -- R_RESULTADO:=5;
    --END IF;      
   END INSERTARDETALLECOMISION;  
   
   PROCEDURE LISTARPERSONAL(
      P_FILTERS IN VARCHAR2,
      R_RESULTADO OUT REF_TYPE
    )
    AS
    V_SQL VARCHAR2(3072);
    BEGIN
          V_SQL := 'SELECT 
                      VCODIGO,
                      IIDEMPLEADO,
                      VEMPLEADO,
                      IIDOFICINA
                    FROM C##PERSONAL.V_EMPLEADO 
           WHERE 1=1 AND BHABILITADO=1' || P_FILTERS;
          OPEN R_RESULTADO FOR V_SQL;
    END LISTARPERSONAL;   
    
   PROCEDURE LISTAR(
    P_LIMIT IN NUMBER,
    P_START IN NUMBER,
    P_SORT IN VARCHAR2,
    P_FILTERS IN VARCHAR2,
    R_RESULTADO OUT REF_TYPE,
    R_TOTAL OUT NUMBER  
  )AS
   V_SQL VARCHAR2(4000);    
    V_MAX NUMBER;
    V_MIN NUMBER;
  BEGIN 
    -- OBTENEMOS EL NÚMERO TOTAL DE REGISTROS
      V_SQL := 'SELECT  COUNT(*)
                FROM    V_COMISION       
                WHERE   1 = 1' || P_FILTERS; 
      EXECUTE IMMEDIATE V_SQL INTO R_TOTAL;

      -- OBTENEMOS EL RANGO DE REGISTROS A MOSTRAR
      IF (P_START IS NOT NULL AND P_LIMIT IS NOT NULL) THEN
        V_MAX := P_START + P_LIMIT;
        V_MIN := (P_START + 1);
      ELSE
        V_MAX := R_TOTAL;
        V_MIN := 0;
      END IF;

      -- OBTENEMOS LA LISTA DE REGISTROS
      V_SQL := 'SELECT  *
                FROM    V_COMISION
                WHERE   1 = 1'|| P_FILTERS || P_SORT ||'
                OFFSET  '|| P_START ||' ROWS FETCH NEXT ' || P_LIMIT || ' ROWS ONLY';
                
      OPEN R_RESULTADO FOR V_SQL;  
  END LISTAR;
  
  PROCEDURE LISTARDETALLEPERSONAL(
    P_LIMIT IN NUMBER,
    P_START IN NUMBER,
    P_SORT IN VARCHAR2,
    P_FILTERS IN VARCHAR2,
    R_RESULTADO OUT REF_TYPE,
    R_TOTAL OUT NUMBER  
  )AS
   V_SQL VARCHAR2(4000);    
    V_MAX NUMBER;
    V_MIN NUMBER;
  BEGIN 
    -- OBTENEMOS EL NÚMERO TOTAL DE REGISTROS
      V_SQL := ' SELECT 
                    COUNT(*)
                FROM DETALLE_COMISION DC  
                INNER JOIN C##PERSONAL.V_EMPLEADO VE ON DC.IIDEMPLEADO=VE.IIDEMPLEADO      
                WHERE  1 = 1' || P_FILTERS; 
      EXECUTE IMMEDIATE V_SQL INTO R_TOTAL;

      -- OBTENEMOS EL RANGO DE REGISTROS A MOSTRAR
      IF (P_START IS NOT NULL AND P_LIMIT IS NOT NULL) THEN
        V_MAX := P_START + P_LIMIT;
        V_MIN := (P_START + 1);
      ELSE
        V_MAX := R_TOTAL;
        V_MIN := 0;
      END IF;

      -- OBTENEMOS LA LISTA DE REGISTROS
      V_SQL := 'SELECT  *
                FROM    ( SELECT  A.*, ROWNUM RNUM
                          FROM    ( SELECT 
                                        DC.IIDCOMISION,
                                        VE.VCODIGO,
                                        VE.IIDEMPLEADO,
                                        VE.VEMPLEADO
                                    FROM DETALLE_COMISION DC  
                                    INNER JOIN C##PERSONAL.V_EMPLEADO VE ON DC.IIDEMPLEADO=VE.IIDEMPLEADO
                                    WHERE  1 = 1'|| P_FILTERS || P_SORT ||') A
                          WHERE   ROWNUM <=' || V_MAX || ') 
                WHERE   RNUM >= ' || V_MIN;
      OPEN R_RESULTADO FOR V_SQL;  
  END LISTARDETALLEPERSONAL;
    
 /* PROCEDURE ELIMINAREMPLEADO(
      P_IIDEMPLEADO IN NUMBER,
      P_IIDCOMISION IN NUMBER
  ) AS
  BEGIN
    DELETE FROM DETALLE_COMISION
    WHERE IIDEMPLEADO=P_IIDEMPLEADO AND IIDCOMISION=P_IIDCOMISION;            
  END ELIMINAREMPLEADO;*/
  
  PROCEDURE EDITAR(
    P_IIDCOMSION IN NUMBER,
    P_VDESCRIPCION IN VARCHAR2,
    P_IIDOCUMENTO IN NUMBER,
    P_VDOCUMENTO IN VARCHAR2,
    P_DFECHASALIDA IN TIMESTAMP,
    P_DFECHARETORNO IN TIMESTAMP,
    P_DFECHADOCUMENTO IN TIMESTAMP,
    P_IIDPAIS IN NUMBER,
    P_IIDDEPARTAMENTO IN NUMBER,
    P_IIDPROVINCIA IN NUMBER,
    P_IIDDISTRITO IN NUMBER,  
    P_IIDOFICINA IN NUMBER,
    P_IIDUSUARIOREGISTRA IN NUMBER,
    R_RESULTADO OUT NUMBER
  )AS
  BEGIN
    UPDATE COMISION SET
      VDESCRIPCION=P_VDESCRIPCION,
      IIDOCUMENTO=P_IIDOCUMENTO,
      VDOCUMENTO=P_VDOCUMENTO,
      DFECHASALIDA=P_DFECHASALIDA,
      DFECHARETORNO=P_DFECHARETORNO,
      DFECHADOCUMENTO=P_DFECHADOCUMENTO,
      IIDPAIS=P_IIDPAIS,
      IIDDEPARTAMENTO=P_IIDDEPARTAMENTO,
      IIDPROVINCIA=P_IIDPROVINCIA,
      IIDDISTRITO=P_IIDDISTRITO,
      IIDOFICINA = P_IIDOFICINA,
      IIDUSUARIOEDITA=P_IIDUSUARIOREGISTRA,
      DFECHAEDITA=SYSDATE
   WHERE IIDCOMISION=P_IIDCOMSION; 
   
   DELETE FROM DETALLE_COMISION WHERE IIDCOMISION = P_IIDCOMSION;
   
   R_RESULTADO := 1;
  END EDITAR;
  
  /*PROCEDURE EDITARDETALLECOMISION(
    P_IIDCOMISION IN NUMBER,
    P_IIDEMPLEADO IN NUMBER   
  )AS
  V_TOTAL INT;
  BEGIN  
      SELECT COUNT(*) INTO V_TOTAL FROM DETALLE_COMISION WHERE IIDCOMISION = P_IIDCOMISION AND IIDEMPLEADO = P_IIDEMPLEADO;
      IF(V_TOTAL=0) THEN
        INSERT INTO DETALLE_COMISION(IIDCOMISION,IIDEMPLEADO,DFECHAREGISTRA) VALUES(P_IIDCOMISION,P_IIDEMPLEADO, SYSDATE);        
      END IF; 
  END EDITARDETALLECOMISION;*/
  
  PROCEDURE INSERTARHISTORIALCOMISION(
    P_IIDCOMISION IN NUMBER,
    P_IIDUSUARIO IN NUMBER,
    P_IIDESTADO IN NUMBER
  )AS
  BEGIN
      INSERT INTO HISTORIAL_COMISION(IIDCOMISION,IIDESTADO,IIDUSUARIO,DFECHA) VALUES(P_IIDCOMISION,P_IIDESTADO,P_IIDUSUARIO,SYSDATE);
  END INSERTARHISTORIALCOMISION;
  
  PROCEDURE INSERTARAMPLIARHIST_COMISION(
    P_IIDCOMISIONANTERIOR IN NUMBER,
    P_IIDCOMISIONNUEVO IN NUMBER,
    P_IIDUSUARIO IN NUMBER,
    R_RESULTADO OUT NUMBER
  )AS 
  BEGIN
        INSERT INTO HISTORIAL_COMISION(IIDCOMISION,IIDESTADO,IIDUSUARIO,DFECHA) VALUES(P_IIDCOMISIONANTERIOR,5,P_IIDUSUARIO,SYSDATE);
        UPDATE COMISION SET
          IIDAMPLIADO=1
        WHERE IIDCOMISION=P_IIDCOMISIONANTERIOR;     
        INSERT INTO HISTORIAL_COMISION(IIDCOMISION,IIDESTADO,IIDUSUARIO,DFECHA) VALUES(P_IIDCOMISIONNUEVO,1,P_IIDUSUARIO,SYSDATE);            
        R_RESULTADO:=0;
        --P_IIDCOMISIONNUEVO;--0 ERA
  END INSERTARAMPLIARHIST_COMISION;
  
  PROCEDURE LISTARHISTORIALCOMISION(
    P_FILTERS IN VARCHAR2,
    R_RESULTADO OUT REF_TYPE
  )AS
  V_SQL VARCHAR2(3072); 
  BEGIN
      V_SQL := 'SELECT 
                      DISTINCT
                      HC.IIDCOMISION,
                      HC.IIDESTADO,
                      CASE 
                       WHEN HC.IIDESTADO=1 THEN ''PENDIENTE''
                       WHEN HC.IIDESTADO=2 THEN ''APROBADO''
                       WHEN HC.IIDESTADO=3 THEN ''DENEGADO''
                       WHEN HC.IIDESTADO=4 THEN ''ANULADO''
                       WHEN HC.IIDESTADO=5 THEN ''AMPLIADO''
                      END AS VESTADO, 
                      HC.IIDUSUARIO,
                      P.VAPEPATERNO || '' '' || P.VAPEMATERNO || '' '' || P.VNOMBRE AS NOMBRES,                      
                      HC.DFECHA,
                      HC.VDESCRIPCION
                  FROM HISTORIAL_COMISION HC 
                  --INNER JOIN C##SEGURIDAD.V_USUARIO U ON HC.IIDUSUARIO=U.IIDUSUARIO
                INNER JOIN C##SEGURIDAD.USUARIO U ON HC.IIDUSUARIO = U.IIDUSUARIO
                INNER JOIN C##PERSONAL.PERSONA P ON U.IIDPERSONA = P.IIDPERSONA
                INNER JOIN ESTADO E ON HC.IIDESTADO=E.IIDESTADO
                WHERE 1=1'||P_FILTERS ||' ORDER BY IIDESTADO';
      OPEN R_RESULTADO FOR V_SQL;
  END;
  
  PROCEDURE APROBAR(
    P_IIDCOMISION IN NUMBER,
    P_IIDUSUARIOREGISTRA IN NUMBER,
    R_RESULTADO OUT NUMBER
  )AS 
  BEGIN
    INSERT INTO HISTORIAL_COMISION(IIDCOMISION,IIDESTADO,IIDUSUARIO,DFECHA)VALUES(P_IIDCOMISION,2,P_IIDUSUARIOREGISTRA,SYSDATE)
    RETURNING IIDCOMISION INTO R_RESULTADO;
    
    UPDATE COMISION SET IIDESTADO = 2, IIDUSUARIOEDITA = P_IIDUSUARIOREGISTRA, DFECHAEDITA = SYSDATE WHERE IIDCOMISION = P_IIDCOMISION;
  END APROBAR; 
  
  PROCEDURE ELIMINARDENEGARANULAR(
    P_IIDCOMISION IN NUMBER,
    P_IIFLAG IN NUMBER,
    P_VDESCRIPCION IN VARCHAR2,
    P_IIDUSUARIOREGISTRA IN NUMBER,
    R_RESULTADO OUT NUMBER  
  )AS
  BEGIN
   CASE  
      WHEN  P_IIFLAG=1 THEN --ELIMINAR
        UPDATE COMISION SET
            BHABILITADO=0,
            IIDUSUARIOEDITA=P_IIDUSUARIOREGISTRA,
            DFECHAEDITA=SYSDATE
        WHERE IIDCOMISION=P_IIDCOMISION;
         R_RESULTADO:=1;
         
      WHEN P_IIFLAG=3 THEN --DENEGAR 
         INSERT INTO HISTORIAL_COMISION(IIDCOMISION,IIDESTADO,IIDUSUARIO,DFECHA,VDESCRIPCION) VALUES(P_IIDCOMISION,3,P_IIDUSUARIOREGISTRA,SYSDATE,P_VDESCRIPCION);
         UPDATE COMISION SET IIDESTADO = 3, IIDUSUARIOEDITA = P_IIDUSUARIOREGISTRA, DFECHAEDITA = SYSDATE WHERE IIDCOMISION = P_IIDCOMISION;
         R_RESULTADO:=1;
         
      WHEN  P_IIFLAG=4 THEN --ANULAR        
        INSERT INTO HISTORIAL_COMISION(IIDCOMISION,IIDESTADO,IIDUSUARIO,DFECHA,VDESCRIPCION) VALUES(P_IIDCOMISION,4,P_IIDUSUARIOREGISTRA,SYSDATE,P_VDESCRIPCION);
        UPDATE COMISION SET IIDESTADO = 4, IIDUSUARIOEDITA = P_IIDUSUARIOREGISTRA, DFECHAEDITA = SYSDATE WHERE IIDCOMISION = P_IIDCOMISION;
        R_RESULTADO:=1;
  END CASE;  
  END ELIMINARDENEGARANULAR;

END USP_COMISION;

/
