DECLARE
  V_DV_IDVENTA    INTEGER;
  V_DV_IDPRODUCTO INTEGER;
  V_DV_CANTIDAD   INTEGER;
  V_DV_PRECIO     INTEGER;
  V_MENSAJE       VARCHAR2(100);
BEGIN
  -- INGRESANDO DATOS
  V_DV_IDVENTA    := 2;
  V_DV_IDPRODUCTO := 2;
  V_DV_CANTIDAD   := 100;
  V_DV_PRECIO     := 500;
  -- PROCESO
  PKG_GENERAR_VENTA.SP_CREAR_VENTA(V_DV_IDVENTA, V_DV_IDPRODUCTO, V_DV_CANTIDAD, V_DV_PRECIO, V_MENSAJE);
  -- MOSTRAR MENSAJE
  dbms_output.put_line(V_MENSAJE);
END;
/

SELECT * FROM tbl_detalle_venta;