-- =============================================
-- CRACIÓN DEL USUARIO SISUNI
-- =============================================
DECLARE
	N INT;
	COMMAND VARCHAR2(200);
BEGIN
	COMMAND := 'DROP USER SISUNI CASCADE';
	SELECT COUNT(*) INTO N
	FROM DBA_USERS
	WHERE USERNAME = 'SISUNI';
	IF ( N = 1 ) THEN
		EXECUTE IMMEDIATE COMMAND;
	END IF;
END;
/

alter session set "_ORACLE_SCRIPT"=true;
CREATE USER SISUNI IDENTIFIED BY uni1219;

GRANT CONNECT, RESOURCE TO SISUNI;

ALTER USER SISUNI
QUOTA UNLIMITED ON USERS;

GRANT CREATE VIEW TO SISUNI;


-- ======================================================
-- CREAR TABLA SISUNI.TBL_PUESTO
-- ======================================================

CREATE TABLE SISUNI.TBL_PUESTO (
P_IDPUESTO INTEGER NOT NULL ,
P_NOMBRE VARCHAR2(25) NOT NULL,
P_ESTADO CHAR(1) NOT NULL,
CONSTRAINT TBL_PUESTO_PK PRIMARY KEY (P_IDPUESTO)
);

-- ======================================================
-- CREAR TABLA SISUNI.TBL_CATEGORIA
-- ======================================================

CREATE TABLE SISUNI.TBL_CATEGORIA (
C_IDCATEGORIA INTEGER NOT NULL ,
C_NOMBRE VARCHAR2(25) NOT NULL,
C_ESTADO CHAR(1) NOT NULL,
CONSTRAINT TBL_CATEGORIA_PK PRIMARY KEY (C_IDCATEGORIA)
);

-- ======================================================
-- CREAR TABLA SISUNI.TBL_MARCA
-- ======================================================

CREATE TABLE SISUNI.TBL_MARCA (
M_IDMARCA INTEGER NOT NULL ,
M_NOMBRE VARCHAR2(25) NOT NULL,
M_ESTADO CHAR(1) NOT NULL,
CONSTRAINT TBL_MARCA_PK PRIMARY KEY (M_IDMARCA)
);

-- ======================================================
-- CREAR TABLA SISUNI.TBL_CLIENTE
-- ======================================================

CREATE TABLE SISUNI.TBL_CLIENTE (
CL_IDCLIENTE INTEGER NOT NULL ,
CL_DNI VARCHAR2 (8) NOT NULL,
CL_NOMBRE VARCHAR2(25),
CL_TELEFONO VARCHAR2(9),
CL_SEXO VARCHAR2(1),
CL_FECHA_NAC DATE,
CL_DIRECCION VARCHAR2(50),
CONSTRAINT TBL_CLIENTE_PK PRIMARY KEY (CL_IDCLIENTE)
);

-- ======================================================
-- CREAR TABLA SISUNI.TBL_EMPLEADO
-- ======================================================

CREATE TABLE SISUNI.TBL_EMPLEADO (
E_IDEMPLEADO INTEGER NOT NULL ,
E_DNI VARCHAR2 (8) NOT NULL,
E_NOMBRE VARCHAR2(25),
E_TELEFONO VARCHAR2(9),
E_SEXO VARCHAR2(1),
E_DIRECCION VARCHAR2(50),
E_FECHA_ING DATE,
E_SALARIO DECIMAL(7,2),
E_ESTADO CHAR(1) NOT NULL,
E_IDPUESTO INTEGER NOT NULL,
CONSTRAINT TBL_EMPLEADO PRIMARY KEY (E_IDEMPLEADO),
CONSTRAINT EMPLEADO_CARGO_FK FOREIGN KEY (E_IDPUESTO) REFERENCES SISUNI.TBL_PUESTO(P_IDPUESTO)
);

-- ======================================================
-- CREAR TABLA SISUNI.TBL_VENTA
-- ======================================================

CREATE TABLE SISUNI.TBL_VENTA (
V_IDVENTA INTEGER NOT NULL ,
V_FECHA_VT DATE,
V_IDEMPLEADO INTEGER NOT NULL,
V_IDCLIENTE INTEGER NOT NULL,
CONSTRAINT TBL_VENTA_PK PRIMARY KEY (V_IDVENTA),
CONSTRAINT VENTA_EMPLEADO_FK FOREIGN KEY (V_IDEMPLEADO) REFERENCES SISUNI.TBL_EMPLEADO(E_IDEMPLEADO),
CONSTRAINT VENTA_CLIENTE_FK FOREIGN KEY (V_IDCLIENTE) REFERENCES SISUNI.TBL_CLIENTE(CL_IDCLIENTE)
);

-- ======================================================
-- CREAR TABLA SISUNI.TBL_PRODUCTO
-- ======================================================

CREATE TABLE SISUNI.TBL_PRODUCTO (
PR_IDPRODUCTO INTEGER NOT NULL ,
PR_NOMBRE VARCHAR2(30),
PR_COSTO NUMBER (7,2),
PR_STOCK NUMBER(5),
PR_IDMARCA INTEGER NOT NULL,
PR_IDCATEGORIA INTEGER NOT NULL,
CONSTRAINT TBL_PRODUCTO_PK PRIMARY KEY (PR_IDPRODUCTO),
CONSTRAINT PRODUCTO_MARCA_FK FOREIGN KEY (PR_IDMARCA) REFERENCES SISUNI.TBL_MARCA(M_IDMARCA),
CONSTRAINT PRODUCTO_CATEGORIA_FK FOREIGN KEY (PR_IDCATEGORIA) REFERENCES SISUNI.TBL_CATEGORIA(C_IDCATEGORIA)
);

-- ======================================================
-- CREAR TABLA SISUNI.TBL_DETALLE_VENTA
-- ======================================================

CREATE TABLE SISUNI.TBL_DETALLE_VENTA (
DV_IDVENTA INTEGER NOT NULL ,
DV_IDPRODUCTO INTEGER  NOT NULL,
DV_CANTIDAD NUMBER (5),
DV_PRECIO NUMBER(7,2),
CONSTRAINT DETALLE_VENTA_VENTA_FK FOREIGN KEY (DV_IDVENTA) REFERENCES SISUNI.TBL_VENTA(V_IDVENTA),
CONSTRAINT DETALLE_VENTA_PRODUCTO_FK FOREIGN KEY (DV_IDPRODUCTO) REFERENCES SISUNI.TBL_PRODUCTO(PR_IDPRODUCTO)
);